### ISSUE TITLE
proxy error with ST 2 RC 

### ISSUE THREAD

**Issue by fdjean** [tomalex0/SenchaTouch-v2-SqliteProxy#2]
sencha touch 2 RC 
Chrome : ok 
Android : ok
Safari (desktop and mobile) :
TypeError: Type error   SqliteProxy.js:137

**Comment by tomalex0** [comment]
Hi Can you please check if the error still exists?

**Comment by fdjean** [comment]
Hi, same with last Sencha version

**Comment by tomalex0** [comment]
Please go through the comments regarding this issue in http://www.sencha.com/forum/showthread.php?151444-SqliteProxy-for-ST2&p=752272&posted=1#post752272.

**Comment by tomalex0** [comment]
Please try with latest version and do let me know if there is any issue. Refer README
